<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * Checkout payment request
 */
class CreateCheckoutPaymentRequest implements JsonSerializable
{
    /**
     * Accepted Payment Methods
     * @required
     * @maps accepted_payment_methods
     * @var array $acceptedPaymentMethods public property
     */
    public $acceptedPaymentMethods;

    /**
     * Success url
     * @required
     * @maps success_url
     * @var string $successUrl public property
     */
    public $successUrl;

    /**
     * Default payment method
     * @maps default_payment_method
     * @var string|null $defaultPaymentMethod public property
     */
    public $defaultPaymentMethod;

    /**
     * Gateway Affiliation Id
     * @maps gateway_affiliation_id
     * @var string|null $gatewayAffiliationId public property
     */
    public $gatewayAffiliationId;

    /**
     * Card payment request
     * @maps credit_card
     * @var CreateCheckoutCardPaymentRequest|null $creditCard public property
     */
    public $creditCard;

    /**
     * Boleto payment request
     * @var CreateCheckoutBoletoPaymentRequest|null $boleto public property
     */
    public $boleto;

    /**
     * Constructor to set initial or default values of member properties
     * @param array                              $acceptedPaymentMethods Initialization value for $this-
     *                                                                     >acceptedPaymentMethods
     * @param string                             $successUrl             Initialization value for $this->successUrl
     * @param string                             $defaultPaymentMethod   Initialization value for $this-
     *                                                                     >defaultPaymentMethod
     * @param string                             $gatewayAffiliationId   Initialization value for $this-
     *                                                                     >gatewayAffiliationId
     * @param CreateCheckoutCardPaymentRequest   $creditCard             Initialization value for $this->creditCard
     * @param CreateCheckoutBoletoPaymentRequest $boleto                 Initialization value for $this->boleto
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->acceptedPaymentMethods = func_get_arg(0);
            $this->successUrl             = func_get_arg(1);
            $this->defaultPaymentMethod   = func_get_arg(2);
            $this->gatewayAffiliationId   = func_get_arg(3);
            $this->creditCard             = func_get_arg(4);
            $this->boleto                 = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['accepted_payment_methods'] = $this->acceptedPaymentMethods;
        $json['success_url']              = $this->successUrl;
        $json['default_payment_method']   = $this->defaultPaymentMethod;
        $json['gateway_affiliation_id']   = $this->gatewayAffiliationId;
        $json['credit_card']              = $this->creditCard;
        $json['boleto']                   = $this->boleto;

        return $json;
    }
}
