<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * Request for creating a new customer
 */
class CreateCustomerRequest implements JsonSerializable
{
    /**
     * Name
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Email
     * @required
     * @var string $email public property
     */
    public $email;

    /**
     * Phone number. Only numbers, no special characters.
     * @required
     * @var string $phone public property
     */
    public $phone;

    /**
     * Document number. Only numbers, no special characters.
     * @required
     * @var string $document public property
     */
    public $document;

    /**
     * Person type. Can be either 'individual' or 'company'
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * The customer's address
     * @required
     * @var CreateAddressRequest $address public property
     */
    public $address;

    /**
     * Metadata
     * @required
     * @var array $metadata public property
     */
    public $metadata;

    /**
     * Constructor to set initial or default values of member properties
     * @param string               $name     Initialization value for $this->name
     * @param string               $email    Initialization value for $this->email
     * @param string               $phone    Initialization value for $this->phone
     * @param string               $document Initialization value for $this->document
     * @param string               $type     Initialization value for $this->type
     * @param CreateAddressRequest $address  Initialization value for $this->address
     * @param array                $metadata Initialization value for $this->metadata
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->name     = func_get_arg(0);
            $this->email    = func_get_arg(1);
            $this->phone    = func_get_arg(2);
            $this->document = func_get_arg(3);
            $this->type     = func_get_arg(4);
            $this->address  = func_get_arg(5);
            $this->metadata = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']     = $this->name;
        $json['email']    = $this->email;
        $json['phone']    = $this->phone;
        $json['document'] = $this->document;
        $json['type']     = $this->type;
        $json['address']  = $this->address;
        $json['metadata'] = $this->metadata;

        return $json;
    }
}
