<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * Request for creating a usage
 */
class CreateUsageRequest implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $quantity public property
     */
    public $quantity;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $description public property
     */
    public $description;

    /**
     * @todo Write general description for this property
     * @required
     * @maps used_at
     * @var string $usedAt public property
     */
    public $usedAt;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $quantity    Initialization value for $this->quantity
     * @param string  $description Initialization value for $this->description
     * @param string  $usedAt      Initialization value for $this->usedAt
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->quantity    = func_get_arg(0);
            $this->description = func_get_arg(1);
            $this->usedAt      = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['quantity']    = $this->quantity;
        $json['description'] = $this->description;
        $json['used_at']     = $this->usedAt;

        return $json;
    }
}
