<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * The settings for creating a credit card payment
 */
class CreateCreditCardPaymentRequest implements JsonSerializable
{
    /**
     * Number of installments
     * @required
     * @var integer $installments public property
     */
    public $installments;

    /**
     * The text that will be shown on the credit card's statement
     * @required
     * @maps statement_descriptor
     * @var string $statementDescriptor public property
     */
    public $statementDescriptor;

    /**
     * Credit card data
     * @required
     * @var CreateCardRequest $card public property
     */
    public $card;

    /**
     * Number of retries
     * @required
     * @var integer $retries public property
     */
    public $retries;

    /**
     * Indicates if the card from the subscription must be updated
     * @required
     * @maps update_subscription_card
     * @var bool $updateSubscriptionCard public property
     */
    public $updateSubscriptionCard;

    /**
     * The credit card id
     * @required
     * @maps card_id
     * @var string $cardId public property
     */
    public $cardId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps card_token
     * @var string $cardToken public property
     */
    public $cardToken;

    /**
     * Indicates a recurrence
     * @required
     * @var bool $recurrence public property
     */
    public $recurrence;

    /**
     * Indicates if the operation should be only authorization or auth and capture.
     * @var bool|null $capture public property
     */
    public $capture;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer           $installments           Initialization value for $this->installments
     * @param string            $statementDescriptor    Initialization value for $this->statementDescriptor
     * @param CreateCardRequest $card                   Initialization value for $this->card
     * @param integer           $retries                Initialization value for $this->retries
     * @param bool              $updateSubscriptionCard Initialization value for $this->updateSubscriptionCard
     * @param string            $cardId                 Initialization value for $this->cardId
     * @param string            $cardToken              Initialization value for $this->cardToken
     * @param bool              $recurrence             Initialization value for $this->recurrence
     * @param bool              $capture                Initialization value for $this->capture
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 9:
                $this->installments           = func_get_arg(0);
                $this->statementDescriptor    = func_get_arg(1);
                $this->card                   = func_get_arg(2);
                $this->retries                = func_get_arg(3);
                $this->updateSubscriptionCard = func_get_arg(4);
                $this->cardId                 = func_get_arg(5);
                $this->cardToken              = func_get_arg(6);
                $this->recurrence             = func_get_arg(7);
                $this->capture                = func_get_arg(8);
                break;

            default:
                $this->installments = 1;
                $this->capture = true;
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['installments']             = $this->installments;
        $json['statement_descriptor']     = $this->statementDescriptor;
        $json['card']                     = $this->card;
        $json['retries']                  = $this->retries;
        $json['update_subscription_card'] = $this->updateSubscriptionCard;
        $json['card_id']                  = $this->cardId;
        $json['card_token']               = $this->cardToken;
        $json['recurrence']               = $this->recurrence;
        $json['capture']                  = $this->capture;

        return $json;
    }
}
