<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * Payment data
 */
class CreatePaymentRequest implements JsonSerializable
{
    /**
     * Payment method
     * @required
     * @maps payment_method
     * @var string $paymentMethod public property
     */
    public $paymentMethod;

    /**
     * Settings for credit card payment
     * @required
     * @maps credit_card
     * @var CreateCreditCardPaymentRequest $creditCard public property
     */
    public $creditCard;

    /**
     * Settings for boleto payment
     * @required
     * @var CreateBoletoPaymentRequest $boleto public property
     */
    public $boleto;

    /**
     * Currency. Must be informed using 3 characters
     * @required
     * @var string $currency public property
     */
    public $currency;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                         $paymentMethod Initialization value for $this->paymentMethod
     * @param CreateCreditCardPaymentRequest $creditCard    Initialization value for $this->creditCard
     * @param CreateBoletoPaymentRequest     $boleto        Initialization value for $this->boleto
     * @param string                         $currency      Initialization value for $this->currency
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->paymentMethod = func_get_arg(0);
            $this->creditCard    = func_get_arg(1);
            $this->boleto        = func_get_arg(2);
            $this->currency      = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['payment_method'] = $this->paymentMethod;
        $json['credit_card']    = $this->creditCard;
        $json['boleto']         = $this->boleto;
        $json['currency']       = $this->currency;

        return $json;
    }
}
