<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * Request for creating a subcription
 */
class CreateSubscriptionRequest implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps plan_id
     * @var string $planId public property
     */
    public $planId;

    /**
     * @todo Write general description for this property
     * @required
     * @var CreateCustomerRequest $customer public property
     */
    public $customer;

    /**
     * @todo Write general description for this property
     * @required
     * @var CreateCardRequest $card public property
     */
    public $card;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $code public property
     */
    public $code;

    /**
     * @todo Write general description for this property
     * @required
     * @maps customer_id
     * @var string $customerId public property
     */
    public $customerId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps credit_card_id
     * @var string $creditCardId public property
     */
    public $creditCardId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps credit_card_gateway_id
     * @var string $creditCardGatewayId public property
     */
    public $creditCardGatewayId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps payment_method
     * @var string $paymentMethod public property
     */
    public $paymentMethod;

    /**
     * @todo Write general description for this property
     * @required
     * @maps billing_type
     * @var string $billingType public property
     */
    public $billingType;

    /**
     * @todo Write general description for this property
     * @required
     * @maps statement_descriptor
     * @var string $statementDescriptor public property
     */
    public $statementDescriptor;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $description public property
     */
    public $description;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $currency public property
     */
    public $currency;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $interval public property
     */
    public $interval;

    /**
     * @todo Write general description for this property
     * @required
     * @maps interval_count
     * @var integer $intervalCount public property
     */
    public $intervalCount;

    /**
     * @todo Write general description for this property
     * @required
     * @maps pricing_scheme
     * @var CreatePricingSchemeRequest $pricingScheme public property
     */
    public $pricingScheme;

    /**
     * @todo Write general description for this property
     * @required
     * @var CreateSubscriptionItemRequest[] $items public property
     */
    public $items;

    /**
     * @todo Write general description for this property
     * @required
     * @var CreateShippingRequest $shipping public property
     */
    public $shipping;

    /**
     * @todo Write general description for this property
     * @required
     * @var CreateDiscountRequest[] $discounts public property
     */
    public $discounts;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $metadata public property
     */
    public $metadata;

    /**
     * @todo Write general description for this property
     * @required
     * @var CreateSetupRequest $setup public property
     */
    public $setup;

    /**
     * @todo Write general description for this property
     * @maps billing_day
     * @var integer|null $billingDay public property
     */
    public $billingDay;

    /**
     * @todo Write general description for this property
     * @var integer|null $installments public property
     */
    public $installments;

    /**
     * @todo Write general description for this property
     * @maps start_at
     * @var string|null $startAt public property
     */
    public $startAt;

    /**
     * @todo Write general description for this property
     * @maps minimum_price
     * @var integer|null $minimumPrice public property
     */
    public $minimumPrice;

    /**
     * @todo Write general description for this property
     * @var integer|null $cycles public property
     */
    public $cycles;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                     $planId              Initialization value for $this->planId
     * @param CreateCustomerRequest      $customer            Initialization value for $this->customer
     * @param CreateCardRequest          $card                Initialization value for $this->card
     * @param string                     $code                Initialization value for $this->code
     * @param string                     $customerId          Initialization value for $this->customerId
     * @param string                     $creditCardId        Initialization value for $this->creditCardId
     * @param string                     $creditCardGatewayId Initialization value for $this->creditCardGatewayId
     * @param string                     $paymentMethod       Initialization value for $this->paymentMethod
     * @param string                     $billingType         Initialization value for $this->billingType
     * @param string                     $statementDescriptor Initialization value for $this->statementDescriptor
     * @param string                     $description         Initialization value for $this->description
     * @param string                     $currency            Initialization value for $this->currency
     * @param string                     $interval            Initialization value for $this->interval
     * @param integer                    $intervalCount       Initialization value for $this->intervalCount
     * @param CreatePricingSchemeRequest $pricingScheme       Initialization value for $this->pricingScheme
     * @param array                      $items               Initialization value for $this->items
     * @param CreateShippingRequest      $shipping            Initialization value for $this->shipping
     * @param array                      $discounts           Initialization value for $this->discounts
     * @param array                      $metadata            Initialization value for $this->metadata
     * @param CreateSetupRequest         $setup               Initialization value for $this->setup
     * @param integer                    $billingDay          Initialization value for $this->billingDay
     * @param integer                    $installments        Initialization value for $this->installments
     * @param string                     $startAt             Initialization value for $this->startAt
     * @param integer                    $minimumPrice        Initialization value for $this->minimumPrice
     * @param integer                    $cycles              Initialization value for $this->cycles
     */
    public function __construct()
    {
        if (25 == func_num_args()) {
            $this->planId              = func_get_arg(0);
            $this->customer            = func_get_arg(1);
            $this->card                = func_get_arg(2);
            $this->code                = func_get_arg(3);
            $this->customerId          = func_get_arg(4);
            $this->creditCardId        = func_get_arg(5);
            $this->creditCardGatewayId = func_get_arg(6);
            $this->paymentMethod       = func_get_arg(7);
            $this->billingType         = func_get_arg(8);
            $this->statementDescriptor = func_get_arg(9);
            $this->description         = func_get_arg(10);
            $this->currency            = func_get_arg(11);
            $this->interval            = func_get_arg(12);
            $this->intervalCount       = func_get_arg(13);
            $this->pricingScheme       = func_get_arg(14);
            $this->items               = func_get_arg(15);
            $this->shipping            = func_get_arg(16);
            $this->discounts           = func_get_arg(17);
            $this->metadata            = func_get_arg(18);
            $this->setup               = func_get_arg(19);
            $this->billingDay          = func_get_arg(20);
            $this->installments        = func_get_arg(21);
            $this->startAt             = func_get_arg(22);
            $this->minimumPrice        = func_get_arg(23);
            $this->cycles              = func_get_arg(24);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['plan_id']                = $this->planId;
        $json['customer']               = $this->customer;
        $json['card']                   = $this->card;
        $json['code']                   = $this->code;
        $json['customer_id']            = $this->customerId;
        $json['credit_card_id']         = $this->creditCardId;
        $json['credit_card_gateway_id'] = $this->creditCardGatewayId;
        $json['payment_method']         = $this->paymentMethod;
        $json['billing_type']           = $this->billingType;
        $json['statement_descriptor']   = $this->statementDescriptor;
        $json['description']            = $this->description;
        $json['currency']               = $this->currency;
        $json['interval']               = $this->interval;
        $json['interval_count']         = $this->intervalCount;
        $json['pricing_scheme']         = $this->pricingScheme;
        $json['items']                  = $this->items;
        $json['shipping']               = $this->shipping;
        $json['discounts']              = $this->discounts;
        $json['metadata']               = $this->metadata;
        $json['setup']                  = $this->setup;
        $json['billing_day']            = $this->billingDay;
        $json['installments']           = $this->installments;
        $json['start_at']               = $this->startAt;
        $json['minimum_price']          = $this->minimumPrice;
        $json['cycles']                 = $this->cycles;

        return $json;
    }
}
