<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * Request for creating a new charge
 */
class CreateChargeRequest implements JsonSerializable
{
    /**
     * Code
     * @required
     * @var string $code public property
     */
    public $code;

    /**
     * The amount of the charge, in cents
     * @required
     * @var integer $amount public property
     */
    public $amount;

    /**
     * The customer's id
     * @required
     * @maps customer_id
     * @var string $customerId public property
     */
    public $customerId;

    /**
     * Customer data
     * @required
     * @var CreateCustomerRequest $customer public property
     */
    public $customer;

    /**
     * Payment data
     * @required
     * @var CreatePaymentRequest $payment public property
     */
    public $payment;

    /**
     * Metadata
     * @required
     * @var array $metadata public property
     */
    public $metadata;

    /**
     * The charge due date
     * @maps due_at
     * @var string|null $dueAt public property
     */
    public $dueAt;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                $code       Initialization value for $this->code
     * @param integer               $amount     Initialization value for $this->amount
     * @param string                $customerId Initialization value for $this->customerId
     * @param CreateCustomerRequest $customer   Initialization value for $this->customer
     * @param CreatePaymentRequest  $payment    Initialization value for $this->payment
     * @param array                 $metadata   Initialization value for $this->metadata
     * @param string                $dueAt      Initialization value for $this->dueAt
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->code       = func_get_arg(0);
            $this->amount     = func_get_arg(1);
            $this->customerId = func_get_arg(2);
            $this->customer   = func_get_arg(3);
            $this->payment    = func_get_arg(4);
            $this->metadata   = func_get_arg(5);
            $this->dueAt      = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['code']        = $this->code;
        $json['amount']      = $this->amount;
        $json['customer_id'] = $this->customerId;
        $json['customer']    = $this->customer;
        $json['payment']     = $this->payment;
        $json['metadata']    = $this->metadata;
        $json['due_at']      = $this->dueAt;

        return $json;
    }
}
