<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * Contains the settings for creating a boleto payment
 */
class CreateBoletoPaymentRequest implements JsonSerializable
{
    /**
     * Number of retries
     * @required
     * @var integer $retries public property
     */
    public $retries;

    /**
     * The bank code, containing three characters. The available codes are on the API specification
     * @required
     * @var string $bank public property
     */
    public $bank;

    /**
     * The instructions field that will be printed on the boleto.
     * @required
     * @var string $instructions public property
     */
    public $instructions;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $retries      Initialization value for $this->retries
     * @param string  $bank         Initialization value for $this->bank
     * @param string  $instructions Initialization value for $this->instructions
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->retries      = func_get_arg(0);
            $this->bank         = func_get_arg(1);
            $this->instructions = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['retries']      = $this->retries;
        $json['bank']         = $this->bank;
        $json['instructions'] = $this->instructions;

        return $json;
    }
}
