<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 *Anticipation limits
 */
class GetAnticipationLimitsResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var \MundiAPILib\Models\Max $max public property
     */
    public $max;

    /**
     * @todo Write general description for this property
     * @required
     * @var \MundiAPILib\Models\Min $min public property
     */
    public $min;

    /**
     * Constructor to set initial or default values of member properties
     * @param Max $max Initialization value for $this->max
     * @param Min $min Initialization value for $this->min
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->max = func_get_arg(0);
            $this->min = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['max'] = $this->max;
        $json['min'] = $this->min;

        return $json;
    }
}
