<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * Response object for getting a discount
 */
class GetDiscountResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var double $value public property
     */
    public $value;

    /**
     * @todo Write general description for this property
     * @required
     * @maps discount_type
     * @var string $discountType public property
     */
    public $discountType;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $status public property
     */
    public $status;

    /**
     * @todo Write general description for this property
     * @required
     * @maps created_at
     * @var string $createdAt public property
     */
    public $createdAt;

    /**
     * @todo Write general description for this property
     * @required
     * @var GetSubscriptionResponse $subscription public property
     */
    public $subscription;

    /**
     * @todo Write general description for this property
     * @var integer|null $cycles public property
     */
    public $cycles;

    /**
     * @todo Write general description for this property
     * @maps deleted_at
     * @var string|null $deletedAt public property
     */
    public $deletedAt;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                  $id           Initialization value for $this->id
     * @param double                  $value        Initialization value for $this->value
     * @param string                  $discountType Initialization value for $this->discountType
     * @param string                  $status       Initialization value for $this->status
     * @param string                  $createdAt    Initialization value for $this->createdAt
     * @param GetSubscriptionResponse $subscription Initialization value for $this->subscription
     * @param integer                 $cycles       Initialization value for $this->cycles
     * @param string                  $deletedAt    Initialization value for $this->deletedAt
     */
    public function __construct()
    {
        if (8 == func_num_args()) {
            $this->id           = func_get_arg(0);
            $this->value        = func_get_arg(1);
            $this->discountType = func_get_arg(2);
            $this->status       = func_get_arg(3);
            $this->createdAt    = func_get_arg(4);
            $this->subscription = func_get_arg(5);
            $this->cycles       = func_get_arg(6);
            $this->deletedAt    = func_get_arg(7);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']            = $this->id;
        $json['value']         = $this->value;
        $json['discount_type'] = $this->discountType;
        $json['status']        = $this->status;
        $json['created_at']    = $this->createdAt;
        $json['subscription']  = $this->subscription;
        $json['cycles']        = $this->cycles;
        $json['deleted_at']    = $this->deletedAt;

        return $json;
    }
}
