<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class GetSubscriptionUsagesDetailsResponse implements JsonSerializable
{
    /**
     * Subscription Identifier
     * @required
     * @maps subscription_id
     * @var string $subscriptionId public property
     */
    public $subscriptionId;

    /**
     * Current Invoice Amount
     * @required
     * @maps total_amount
     * @var integer $totalAmount public property
     */
    public $totalAmount;

    /**
     * Period Details
     * @required
     * @maps Period
     * @var \MundiAPILib\Models\GetPeriodResponse $period public property
     */
    public $period;

    /**
     * Usages Details
     * @required
     * @maps Usages
     * @var \MundiAPILib\Models\GetUsageResponse[] $usages public property
     */
    public $usages;

    /**
     * Constructor to set initial or default values of member properties
     * @param string            $subscriptionId Initialization value for $this->subscriptionId
     * @param integer           $totalAmount    Initialization value for $this->totalAmount
     * @param GetPeriodResponse $period         Initialization value for $this->period
     * @param array             $usages         Initialization value for $this->usages
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->subscriptionId = func_get_arg(0);
            $this->totalAmount    = func_get_arg(1);
            $this->period         = func_get_arg(2);
            $this->usages         = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['subscription_id'] = $this->subscriptionId;
        $json['total_amount']    = $this->totalAmount;
        $json['Period']          = $this->period;
        $json['Usages']          = $this->usages;

        return $json;
    }
}
