<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * Response object for getting a usage
 */
class GetUsageResponse implements JsonSerializable
{
    /**
     * Id
     * @required
     * @var string $id public property
     */
    public $id;

    /**
     * Quantity
     * @required
     * @var integer $quantity public property
     */
    public $quantity;

    /**
     * Description
     * @required
     * @var string $description public property
     */
    public $description;

    /**
     * Used at
     * @required
     * @maps used_at
     * @var string $usedAt public property
     */
    public $usedAt;

    /**
     * Creation date
     * @required
     * @maps created_at
     * @var string $createdAt public property
     */
    public $createdAt;

    /**
     * Subscription item
     * @required
     * @maps subscription_item
     * @var GetSubscriptionItemResponse $subscriptionItem public property
     */
    public $subscriptionItem;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                      $id               Initialization value for $this->id
     * @param integer                     $quantity         Initialization value for $this->quantity
     * @param string                      $description      Initialization value for $this->description
     * @param string                      $usedAt           Initialization value for $this->usedAt
     * @param string                      $createdAt        Initialization value for $this->createdAt
     * @param GetSubscriptionItemResponse $subscriptionItem Initialization value for $this->subscriptionItem
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->id               = func_get_arg(0);
            $this->quantity         = func_get_arg(1);
            $this->description      = func_get_arg(2);
            $this->usedAt           = func_get_arg(3);
            $this->createdAt        = func_get_arg(4);
            $this->subscriptionItem = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                = $this->id;
        $json['quantity']          = $this->quantity;
        $json['description']       = $this->description;
        $json['used_at']           = $this->usedAt;
        $json['created_at']        = $this->createdAt;
        $json['subscription_item'] = $this->subscriptionItem;

        return $json;
    }
}
