<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * Request for updating the credit card from a subscription
 */
class UpdateSubscriptionCreditCardRequest implements JsonSerializable
{
    /**
     * Credit card data
     * @required
     * @maps credit_card
     * @var CreateCreditCardRequest $creditCard public property
     */
    public $creditCard;

    /**
     * Credit card id
     * @required
     * @maps credit_card_id
     * @var string $creditCardId public property
     */
    public $creditCardId;

    /**
     * Credit card gateway id
     * @required
     * @maps credit_card_gateway_id
     * @var string $creditCardGatewayId public property
     */
    public $creditCardGatewayId;

    /**
     * Constructor to set initial or default values of member properties
     * @param CreateCreditCardRequest $creditCard          Initialization value for $this->creditCard
     * @param string                  $creditCardId        Initialization value for $this->creditCardId
     * @param string                  $creditCardGatewayId Initialization value for $this->creditCardGatewayId
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->creditCard          = func_get_arg(0);
            $this->creditCardId        = func_get_arg(1);
            $this->creditCardGatewayId = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['credit_card']            = $this->creditCard;
        $json['credit_card_id']         = $this->creditCardId;
        $json['credit_card_gateway_id'] = $this->creditCardGatewayId;

        return $json;
    }
}
