<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * Request for updating an address
 */
class UpdateAddressRequest implements JsonSerializable
{
    /**
     * Number
     * @required
     * @var string $number public property
     */
    public $number;

    /**
     * Complement
     * @required
     * @var string $complement public property
     */
    public $complement;

    /**
     * Metadata
     * @required
     * @var array $metadata public property
     */
    public $metadata;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $number     Initialization value for $this->number
     * @param string $complement Initialization value for $this->complement
     * @param array  $metadata   Initialization value for $this->metadata
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->number     = func_get_arg(0);
            $this->complement = func_get_arg(1);
            $this->metadata   = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['number']     = $this->number;
        $json['complement'] = $this->complement;
        $json['metadata']   = $this->metadata;

        return $json;
    }
}
