<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * Request for updating credit card data
 */
class UpdateChargeCreditCardRequest implements JsonSerializable
{
    /**
     * Indicates if the subscriptions using this card must also be updated
     * @required
     * @maps update_subscription
     * @var bool $updateSubscription public property
     */
    public $updateSubscription;

    /**
     * Credit card id
     * @required
     * @maps credit_card_id
     * @var string $creditCardId public property
     */
    public $creditCardId;

    /**
     * Credit card id on the gateway
     * @required
     * @maps credit_card_gateway_id
     * @var string $creditCardGatewayId public property
     */
    public $creditCardGatewayId;

    /**
     * Credit card data
     * @required
     * @maps credit_card
     * @var CreateCreditCardRequest $creditCard public property
     */
    public $creditCard;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool                    $updateSubscription  Initialization value for $this->updateSubscription
     * @param string                  $creditCardId        Initialization value for $this->creditCardId
     * @param string                  $creditCardGatewayId Initialization value for $this->creditCardGatewayId
     * @param CreateCreditCardRequest $creditCard          Initialization value for $this->creditCard
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->updateSubscription  = func_get_arg(0);
            $this->creditCardId        = func_get_arg(1);
            $this->creditCardGatewayId = func_get_arg(2);
            $this->creditCard          = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['update_subscription']    = $this->updateSubscription;
        $json['credit_card_id']         = $this->creditCardId;
        $json['credit_card_gateway_id'] = $this->creditCardGatewayId;
        $json['credit_card']            = $this->creditCard;

        return $json;
    }
}
