<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 * Request for updating a subscription's payment method
 */
class UpdateSubscriptionPaymentMethodRequest implements JsonSerializable
{
    /**
     * The new payment method
     * @required
     * @maps payment_method
     * @var string $paymentMethod public property
     */
    public $paymentMethod;

    /**
     * Card id
     * @required
     * @maps card_id
     * @var string $cardId public property
     */
    public $cardId;

    /**
     * Card data
     * @required
     * @var CreateCardRequest $card public property
     */
    public $card;

    /**
     * Constructor to set initial or default values of member properties
     * @param string            $paymentMethod Initialization value for $this->paymentMethod
     * @param string            $cardId        Initialization value for $this->cardId
     * @param CreateCardRequest $card          Initialization value for $this->card
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->paymentMethod = func_get_arg(0);
            $this->cardId        = func_get_arg(1);
            $this->card          = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['payment_method'] = $this->paymentMethod;
        $json['card_id']        = $this->cardId;
        $json['card']           = $this->card;

        return $json;
    }
}
